const Router = {
  BOTTOM_STACK: 'BOTTOM/STACK',
  DASHBOARD_TAB: 'BOTTOM/DASHBOARD',
  MESSAGE_TAB: 'BOTTOM/MESSAGE',
  NOTIFICATION_TAB: 'BOTTOM/NOTIFICATION',
  SETTING_TAB: 'BOTTOM/SETTING',
  // Screens
  FORM_SCREEN: 'SCREEN/FORM'
}

export default Router
