const Router = {
  BOTTOM_STACK: 'BOTTOM/STACK',
  DASHBOARD_TAB: 'BOTTOM/DASHBOARD',
  MESSAGE_TAB: 'BOTTOM/MESSAGE',
  NOTIFICATION_TAB: 'BOTTOM/NOTIFICATION',
  SETTING_TAB: 'BOTTOM/SETTING'
}

export default Router
